### ISSUE TITLE
棋盘格生成有问题

### ISSUE THREAD

**Issue by watertianyi** [zsirui/slam-python#1]
这是你的代码生成的棋盘格
![checkerboard](https://user-images.githubusercontent.com/29244715/50470494-a3b4a400-09eb-11e9-95f0-d171806d0398.png)

**Comment by zsirui** [comment]
代码确实存在问题，原本应该生成的是6*8比例的棋盘格，代码中生成逻辑错了，谢谢指出错误

**Comment by zsirui** [comment]
> 这是你的代码生成的棋盘格
> ![checkerboard](https://user-images.githubusercontent.com/29244715/50470494-a3b4a400-09eb-11e9-95f0-d171806d0398.png)

这个问题已经修复了 @honghande
